# Site settings
title: Núcleo Digital
description: Inovação em participação através da Internet
analytics_id: UA-XXXXX-X
email: contato@nucleodigital.cc
github: nucleo-digital
url: http://nucleodigital.cc

collections:
- apresentacao
- objetivos
- cases
- clientes
- depoimentos
- oss
- midia
- equipe

# Build settings
markdown: kramdown

gems: [jekyll-sass-converter]
exclude: ["vendor"]
